name: Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    
    - name: Setup JDK 17
      uses: actions/setup-java@v2.3.1
      with:
          java-version: 17
          distribution: 'temurin'

    - name: Check Version and Build
      env:
        GH_REPO: ${{ github.repository }}
        TEST: true
      run: |
        npm install
        npm start
      
    - name: List files and print output.json
      run: |
        ls -l
        cat ./output.json
      
